# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38df07d0263fd0252b6fc4c8cf5a931adf1287f0f9726fe17a3ee4f794792c682c0812872c7f5cbd8ec57ad97649036d0e37f4c551e50a0b6e5d9c97ccee7266

test:
  secret_key_base: b26ca355caf899219304d1217ad91de528ef8db620154acb253005bab943fc31b32c739db6a739105db10a9f267d3f9631739678b53d152b19efb04b03f5280a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
